# This is a basic workflow to help you get started with Actions

name: addDiscussions

# Controls when the workflow will run
on:
  discussion:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# gets data from discussion

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: sending
        uses: brob/action-add-activity@v1.5.10
        with:
          workspace: ${{ secrets.ORBIT_WORKSPACE }}
          api_key: ${{ secrets.ORBIT_KEY }}
          username: ${{ github.event.discussion.user.login }}
          activity_type: 'discussion:created'
          title: 'Discussion created'
          occured_at: ${{ github.event.discussion.created_at }}
          description: |
            # ${{github.event.discussion.title }} 
            ${{ github.event.discussion.body }}
